# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3url', models.TextField()),
                ('md5sum', models.CharField(db_index=True, max_length=255, unique=True)),
                ('thumb_path', models.TextField()),
            ],
        ),
    ]
