# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumb',
            name='s3url',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
