# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_auto_20171218_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumb',
            name='md5sum',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
