# Generated by Django 2.0.3 on 2018-03-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0004_auto_20180105_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('s3url', models.CharField(db_index=True, max_length=500, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=255)),
                ('name', models.TextField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('s3url', models.CharField(db_index=True, max_length=500, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=255)),
                ('name', models.TextField(blank=True, default='', max_length=255)),
                ('preview_thumb', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
