RECAPTCHA_PUBLIC_KEY = '6Lcg9sQSAAAAACO2DlRTdy2SxI8u539LVRqYL9yF'
RECAPTCHA_PRIVATE_KEY = '6Lcg9sQSAAAAAIErSSyfUrAa5cRSttXLpWSWEQjm'

EMAIL_HOST = 'localhost'
EMAIL_HOST_PASSWORD = ''
EMAIL_HOST_USER = ''
EMAIL_PORT = 1025
